/**
 * Default YES/NO button copy per market. Merged in `withResolutionDefaults` unless overridden.
 */
export const MARKET_SIDE_LABELS = {
  market_1: { yesLabel: "Knicks reach ECF", noLabel: "Knicks miss ECF" },
  market_nba_cavs_raptors_live: {
    yesLabel: "Cleveland",
    noLabel: "Toronto",
    h2h: true,
    yesPicks: "away",
  },
  market_2: { yesLabel: "Dodgers win NL West", noLabel: "Someone else wins" },
  market_3: { yesLabel: "Lakers win next game", noLabel: "Lakers lose next game" },
  market_4: { yesLabel: "Rams score 24+", noLabel: "Rams score ≤23" },
  market_5: { yesLabel: "USC wins ranked game", noLabel: "USC loses ranked game" },
  market_6: { yesLabel: "Goes to extra time", noLabel: "Ends in regulation" },
  market_7: { yesLabel: "Mets score first", noLabel: "Braves score first" },
  market_8: { yesLabel: "Rangers win next game", noLabel: "Rangers lose next game" },
  market_9: { yesLabel: "Fight goes distance", noLabel: "Stoppage before final bell" },
  market_10: { yesLabel: "Warriors win by 8+", noLabel: "Margin under 8 or loss" },
  market_11: { yesLabel: "2+ Yankees HR", noLabel: "≤1 Yankees HR" },
  market_12: { yesLabel: "49ers win NFC West", noLabel: "49ers miss division title" },
  market_13: { yesLabel: "Men's final goes 5 sets", noLabel: "Final ends in 3–4 sets" },
  market_14: { yesLabel: "Chiefs win opener", noLabel: "Chiefs lose or tie" },
  market_15: { yesLabel: "Winner ≤10 under par", noLabel: "Winner worse than 10 under" },
  market_16: { yesLabel: "Pole sitter wins", noLabel: "Someone else wins" },
  market_17: { yesLabel: "Duke reaches Final Four", noLabel: "Duke misses Final Four" },
  market_18: { yesLabel: "USWNT wins opener", noLabel: "Draw or loss" },
  market_25: { yesLabel: "Inter Miami", noLabel: "Another MLS club" },
  market_26: { yesLabel: "Liverpool", noLabel: "Another EPL club" },
  market_27: { yesLabel: "Real Madrid", noLabel: "Another UCL club" },
  market_28: { yesLabel: "Barcelona", noLabel: "Another La Liga club" },
  market_29: { yesLabel: "Inter Milan", noLabel: "Another Serie A club" },
  market_30: { yesLabel: "Portland Thorns", noLabel: "Another NWSL club" },
  market_31: { yesLabel: "Palmeiras", noLabel: "Another Série A club" },
  market_32: { yesLabel: "Alcaraz", noLabel: "Another player" },
  market_33: { yesLabel: "Sinner", noLabel: "Another player" },
  market_34: { yesLabel: "Fritz", noLabel: "Another player" },
  market_35: { yesLabel: "Edmonton", noLabel: "Another NHL team" },
  market_36: { yesLabel: "Coco Gauff", noLabel: "Another player" },
};
