import type { MarketGeneratorResult } from "./types";

export function sportsMarketGenerator(): MarketGeneratorResult {
  return {
    sourceName: "sports-stub",
    markets: [
      {
        question: "Will the Warriors win their next scheduled home game?",
        category: "NBA",
        closeTime: "2026-05-07T02:00:00.000Z",
        resolutionTime: "2026-05-07T06:00:00.000Z",
        resolutionSource: "Official league box score",
        resolutionRules:
          "Resolves YES if Golden State is credited with a win in the official final box score. Resolves NO if they lose. If the game is postponed before tipoff, the market should be closed or regenerated by an admin.",
        externalSourceName: "sports-stub",
        externalSourceId: "warriors-next-home-win-2026-05",
        metadata: {
          sport: "basketball",
          league: "NBA",
          dataProvider: "placeholder",
        },
      },
    ],
  };
}
